### ISSUE TITLE
Zwevende documenten toevoegen aan een stap (dit kan nu nog niet)

### ISSUE THREAD

**Issue by rutgerdik** [Amsterdam/omslagroute#127]
Nu staat er nog een + knop onderaan waarmee je documenten kunt toevoegen die nergens bij horen.

**Comment by rvegt** [comment]
@mguikema ,  zou je het label willen aanpassen naar 'Bij welke processtap hoort dit document?' De dubbele punt achter 'Titel van het document' kan dan ook meteen weg.
